[package]
name = "waves-previewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
eframe = { version = "0.33.3", default-features = false }
egui = "0.33.3"
egui_extras = "0.33.3"
cpal = "0.16"
hound = "3.5"
walkdir = "2.5"
rfd = "0.15.4"
arc-swap = "1.7"
atomic_float = "1"
signalsmith-stretch = "0.1"
image = "0.24"
rustfft = "6"
regex = "1"
symphonia = { version = "0.5.5", default-features = false, features = ["wav", "pcm", "mp3", "isomp4", "aac", "alac"] }
id3 = "1"
mp4ameta = "0.13"
mp3lame-encoder = "0.2.2"
fdk-aac = "0.8"
mp4 = "0.14"
bytes = "1"
egui_kittest = { version = "0.33.3", optional = true, features = ["eframe"] }

[features]
default = ["glow"]
glow = ["eframe/glow"]
wgpu = ["eframe/wgpu"]
kittest = ["egui_kittest"]
