[package]
name = "waves-previewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
eframe = { version = "0.27", features = ["wgpu"] }
egui = "0.27"
egui_extras = "0.27"
cpal = "0.16"
hound = "3.5"
walkdir = "2.5"
rfd = "0.15.4"
arc-swap = "1.7"
atomic_float = "1"
signalsmith-stretch = "0.1"
image = "0.24"
rustfft = "6"
